services:
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data

  server:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info --concurrency=2
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis_data: 